### ISSUE TITLE
Enable gzip compression on www.dokuwiki.org

### ISSUE THREAD

**Issue by issmirnov** [splitbrain/dokuwiki#1749]
I tested www.dokuwiki.org with https://testmysite.thinkwithgoogle.com and the results had many areas to improve. One of the most impactful and quickest changes is enabling gzip compression. 

You can test your change with `curl -s -I -L -H 'Accept-Encoding: gzip,deflate' http://www.dokuwiki.org`

If this is a simple change, would be great to see it done. Should improve page load times and save data for our fellow users abroad.

**Comment by Klap-in** [comment]
Is this question addressed by this question? https://github.com/splitbrain/dokuwiki/issues/1585

**Comment by Klap-in** [comment]
Here it is said that it is already added to some resources, which are indeed compressed. https://github.com/splitbrain/dokuwiki/issues/1161

**Comment by issmirnov** [comment]
I believe #1585 is not relevant, since my issue is pointing out that the apache server for www.dokuwiki.org itself is misconfigured, rather than an issue with the internals of the wiki engine. 

#1161 is a sound suggestion, but still doesn't address the core issue of compression not being enabled on the dokuwiki.org hosts.

Could whoever controls the apache server check the settings? I use nginx to run my wiki, and compression works just fine. This is an infra issue, not a dokuwiki code issue.

Hope this helps!

**Comment by splitbrain** [comment]
The server has mod_deflate enabled. Trying your suggested command results in:

```
$ curl -s -I -L -H 'Accept-Encoding: gzip,deflate' http://www.dokuwiki.org
HTTP/1.1 302 Found
Date: Sun, 13 Nov 2016 10:00:57 GMT
Server: Apache
Location: https://www.dokuwiki.org/
Content-Type: text/html; charset=iso-8859-1

HTTP/1.1 302 Moved Temporarily
Date: Sun, 13 Nov 2016 10:00:58 GMT
Server: Apache
Set-Cookie: DokuWiki=d3vjvboh3sf88j2e6v4ntbtbq6; path=/; secure; HttpOnly
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
Set-Cookie: DW7fa065a06cb74b536c124cfbe56ac6d3=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0; path=/; secure; httponly
Location: https://www.dokuwiki.org/dokuwiki#
Content-Type: text/html; charset=UTF-8

HTTP/1.1 200 OK
Date: Sun, 13 Nov 2016 10:00:58 GMT
Server: Apache
Set-Cookie: DokuWiki=4l71crh0e59hgks71f3070omp0; path=/; secure; HttpOnly
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
Set-Cookie: DW7fa065a06cb74b536c124cfbe56ac6d3=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0; path=/; secure; httponly
Set-Cookie: visitorid=v-582839da1696c5.41410011; expires=Sat, 11-Feb-2017 10:00:58 GMT; Max-Age=7776000; path=/; secure; httponly
X-UA-Compatible: IE=edge,chrome=1
Vary: Accept-Encoding
Content-Encoding: gzip
Content-Type: text/html; charset=utf-8
```

The response contains a ``Content-Encoding: gzip`` gzip header, so I think it is working fine. No idea why the website mentioned by you fails to detect the compression?

**Comment by issmirnov** [comment]
Must be a bug on Google's side.

I tested dokuwiki with https://www.giftofspeed.com/gzip-test/ and [http://checkgzipcompression.com/](http://checkgzipcompression.com/?url=https%3A%2F%2Fwww.dokuwiki.org%2Fdokuwiki), both passed. 

Glad to see this was already handled, my mistake for not cross referencing with other sites. 

Thanks all!
